In [26]:
import torch

import iree.turbine.aot as aot

from iree.compiler.ir import (
    Context,
)

In [ ]:
counter = torch.tensor([0], dtype=torch.int32)


# class Counter_(torch.nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.c = torch.nn.Parameter(
#             torch.tensor([0], dtype=torch.int32), requires_grad=False
#         )

#     def


class Counter(aot.CompiledModule):
    _counter = aot.export_global(counter, mutable=True)
    add = aot.jittable(lambda x, y: x + y)

    def get_counter(self):
        return self._counter

    def set_counter(self, c=aot.AbstractTensor(1, dtype=torch.int32)):
        self._counter = c

    def add_counter(self, c=aot.abstractify(_counter)):
        self._counter = self.add(c, self._counter)


model = Counter()
inst = Counter(context=Context(), import_to="full")

with open("converted_counter.mlir", "w") as f:
    f.write(str(aot.CompiledModule.get_mlir_module(inst)))

In [ ]:
class Counter(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.counter = torch.nn.Parameter(
            torch.tensor([0], dtype=torch.int32), requires_grad=False
        )

    def get_counter(self):
        return self.counter

    def set_counter(self, c):
        self.counter.data = c

    def add_counter(self, c):
        self.counter.data = c + self.counter.data


model = Counter()


model = model.eval()

print(f"{model}")

print(model.get_counter())
model.set_counter(torch.tensor([12], dtype=torch.int32, requires_grad=False))
print(model.get_counter())
model.add_counter(torch.tensor([15], dtype=torch.int32, requires_grad=False))
print(model.get_counter())

# export_output = aot.export(model, dynamic_shapes=)
# compiled_model = torch.compile(model, backend="iree_turbine")

Counter()
Parameter containing:
tensor([0], dtype=torch.int32)
Parameter containing:
tensor([12], dtype=torch.int32)
Parameter containing:
tensor([27], dtype=torch.int32)


<bound method OptimizedModule.__dir__ of OptimizedModule(
  (_orig_mod): Counter()
)>

In [ ]:
class ProcArgsModule(aot.CompiledModule):
    def foobar(self, a=aot.AbstractTensor(3, 2), b=aot.AbstractTensor(1, 1)):
        return b, a


model = ProcArgsModule()
inst = ProcArgsModule(context=Context(), import_to="full")

with open("converted_counter.mlir", "w") as f:
    f.write(str(aot.CompiledModule.get_mlir_module(inst)))